const tg=window.Telegram?.WebApp;try{tg?.ready();tg?.expand();tg?.setHeaderColor?.('#050807');tg?.setBackgroundColor?.('#030605')}catch(e){}
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const key='goodigoo_rush_v02';let s=JSON.parse(localStorage.getItem(key)||'{}');
Object.assign(s,{coins:s.coins??350,xp:s.xp??0,best:s.best??0,runs:s.runs??0,missions:s.missions??0,totalCoins:s.totalCoins??0,dailyDay:s.dailyDay??4,dailyClaimed:s.dailyClaimed??false,inv:s.inv??{shield:0,magnet:0,boost:0}});
const name=tg?.initDataUnsafe?.user?.first_name||'GoodiGoo';
function persist(){localStorage.setItem(key,JSON.stringify(s));render()}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1600)}
function show(id){$$('.screen').forEach(e=>e.classList.remove('active'));$('#'+id).classList.add('active');if(id==='rating')rank()}
$$('[data-screen]').forEach(b=>b.onclick=()=>show(b.dataset.screen));
function info(){let level=Math.floor(s.xp/100)+1,n=s.xp%100;return{level,n,rank:level>=10?'Легенда GoodiGoo':level>=7?'Элита':level>=5?'Ветеран':level>=3?'Свой':level>=2?'В теме':'Новичок'}}
function render(){
 let i=info();$('#wallet').textContent=s.coins;$('#shopWallet').textContent=s.coins;$('#best').textContent=s.best;$('#lvl').textContent=i.level;$('#runs').textContent=s.runs;
 $('#username').textContent=name;$('#profileLvl').textContent=i.level;$('#rankName').textContent=i.rank;$('#xpNow').textContent=i.n;$('#xpFill').style.width=i.n+'%';$('#pBest').textContent=s.best;$('#pRuns').textContent=s.runs;$('#pCoins').textContent=s.coins;$('#pMissions').textContent=s.missions;
 $('#ach1').classList.toggle('unlocked',s.best>=100);$('#ach2').classList.toggle('unlocked',s.totalCoins>=25);$('#ach3').classList.toggle('unlocked',s.best>=500);
 let inv=[];if(s.inv.shield)inv.push(`🛡️ ×${s.inv.shield}`);if(s.inv.magnet)inv.push(`🧲 ×${s.inv.magnet}`);if(s.inv.boost)inv.push(`🚀 ×${s.inv.boost}`);$('#inventory').textContent=inv.join('   ')||'пусто';days()
}
function days(){let vals=[100,150,200,250,300,350,500];$('#days').innerHTML=vals.map((v,k)=>`<div class="day ${k+1<s.dailyDay?'done':k+1===s.dailyDay?'current':''}">ДЕНЬ ${k+1}<b>🪙 ${v}</b></div>`).join('');$('#daily').disabled=s.dailyClaimed;$('#daily').style.opacity=s.dailyClaimed?'.4':'1';$('#daily').textContent=s.dailyClaimed?'УЖЕ ЗАБРАНО':'ЗАБРАТЬ СЕГОДНЯ';$('#streak').textContent=s.dailyDay}
$('#daily').onclick=()=>{if(s.dailyClaimed)return;let v=[100,150,200,250,300,350,500][Math.min(s.dailyDay-1,6)];s.coins+=v;s.dailyClaimed=true;persist();toast(`+${v} GoodiCoin`)};
$$('.shopgrid button').forEach(b=>b.onclick=()=>{let p=+b.dataset.price;if(s.coins<p)return toast('Не хватает GoodiCoin');s.coins-=p;s.inv[b.dataset.item]++;persist();toast('Буст куплен')});
function rank(){let a=[['SHADOW',Math.max(1105,s.best+420)],['NEO',Math.max(980,s.best+250)],['FASTBOY',Math.max(875,s.best+120)],[name,s.best]].sort((a,b)=>b[1]-a[1]);$('#ranklist').innerHTML=a.map((x,k)=>`<div class="rankrow ${x[0]===name?'me':''}"><b>#${k+1}</b><span>${x[0]}</span><b>${x[1]} м</b></div>`).join('')}
const c=$('#canvas'),x=c.getContext('2d');let W,H,dpr,g,raf,last;
function resize(){let r=c.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);c.width=r.width*dpr;c.height=r.height*dpr;W=r.width;H=r.height;x.setTransform(dpr,0,0,dpr,0,0)}
function start(){show('game');setTimeout(()=>{resize();g={run:true,pause:false,t:0,speed:300,dist:s.inv.boost?20:0,coins:0,passed:0,shield:s.inv.shield?1:0,magnet:!!s.inv.magnet,p:{x:68,y:H-145,w:42,h:58,vy:0,ground:true},obs:[],cs:[],no:.9,nc:.45};if(s.inv.shield)s.inv.shield--;if(s.inv.magnet)s.inv.magnet--;if(s.inv.boost)s.inv.boost--;persist();last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)},50)}
$('#play').onclick=start;$('#again').onclick=start;$('#pause').onclick=()=>{if(g){g.pause=!g.pause;$('#pause').textContent=g.pause?'▶':'Ⅱ'}};
c.onpointerdown=()=>{if(g?.run&&!g.pause&&g.p.ground){g.p.vy=-610;g.p.ground=false;try{tg?.HapticFeedback?.impactOccurred('light')}catch(e){}}};
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function loop(t){if(!g?.run)return;let dt=Math.min((t-last)/1000,.032);last=t;if(!g.pause)update(dt);draw();raf=requestAnimationFrame(loop)}
function update(dt){g.t+=dt;g.speed+=dt*3.5;g.dist+=g.speed*dt/43;let p=g.p;p.vy+=1550*dt;p.y+=p.vy*dt;let gy=H-94-p.h;if(p.y>=gy){p.y=gy;p.vy=0;p.ground=true}g.no-=dt;if(g.no<=0){let h=40+Math.random()*45;g.obs.push({x:W+25,y:H-94-h,w:32+Math.random()*22,h,passed:false});g.no=.85+Math.random()*.75}g.nc-=dt;if(g.nc<=0){for(let j=0;j<3+Math.random()*3;j++)g.cs.push({x:W+30+j*34,y:H-155-Math.random()*95,r:9});g.nc=.75+Math.random()*.8}g.obs.forEach(o=>{o.x-=g.speed*dt;if(!o.passed&&o.x+o.w<p.x){o.passed=true;g.passed++}});g.cs.forEach(q=>{q.x-=g.speed*dt;if(g.magnet&&q.x<W*.75){q.x+=(p.x-q.x)*dt*4;q.y+=(p.y-q.y)*dt*4}});for(let o of g.obs)if(hit(p,o)){if(g.shield){g.shield=0;o.x=-999;toast('🛡️ Щит спас')}else return end()}g.cs=g.cs.filter(q=>{if(Math.hypot(p.x+p.w/2-q.x,p.y+p.h/2-q.y)<30){g.coins++;return false}return q.x>-20});g.obs=g.obs.filter(o=>o.x>-80);$('#meters').textContent=Math.floor(g.dist);$('#runCoins').textContent=g.coins;$('#missionProgress').textContent=Math.min(g.passed,5)+'/5'}
function draw(){let z=x.createLinearGradient(0,0,0,H);z.addColorStop(0,'#151032');z.addColorStop(.45,'#101a31');z.addColorStop(1,'#06100b');x.fillStyle=z;x.fillRect(0,0,W,H);
 let sc=(g.dist*2.4)%78;x.fillStyle='#0a1730';for(let i=-1;i<9;i++){let xx=i*78-sc,hh=110+(i%4)*35;x.fillRect(xx,H-94-hh,62,hh);x.fillStyle='#6c4a2e';for(let yy=H-110-hh;yy<H-115;yy+=25)for(let wx=xx+11;wx<xx+52;wx+=18)x.fillRect(wx,yy,5,7);x.fillStyle='#0a1730'}x.strokeStyle='#59ff2438';x.lineWidth=1;for(let i=0;i<8;i++){x.beginPath();x.moveTo(W/2,H-205);x.lineTo(i*W/7,H-94);x.stroke()}x.fillStyle='#070b0b';x.fillRect(0,H-94,W,94);x.fillStyle='#315637';x.fillRect(0,H-96,W,3);
 g.obs.forEach(o=>{x.fillStyle='#242a30';x.fillRect(o.x,o.y,o.w,o.h);x.strokeStyle='#ff5d3d';x.lineWidth=2;x.strokeRect(o.x+3,o.y+3,o.w-6,o.h-6);x.beginPath();x.moveTo(o.x+6,o.y+6);x.lineTo(o.x+o.w-6,o.y+o.h-6);x.moveTo(o.x+o.w-6,o.y+6);x.lineTo(o.x+6,o.y+o.h-6);x.stroke()});g.cs.forEach(q=>{x.beginPath();x.arc(q.x,q.y,q.r,0,7);x.fillStyle='#ffc52b';x.shadowBlur=13;x.shadowColor='#ffc52b';x.fill();x.shadowBlur=0;x.fillStyle='#6d4a00';x.font='bold 11px Arial';x.textAlign='center';x.textBaseline='middle';x.fillText('G',q.x,q.y)});
 let p=g.p;x.save();x.translate(p.x,p.y);x.shadowBlur=18;x.shadowColor='#6cff20';x.fillStyle='#0a0e0b';x.beginPath();x.arc(21,20,22,0,7);x.fill();x.shadowBlur=0;x.fillStyle='#111912';x.fillRect(7,34,29,24);x.fillStyle='#6dff1c';x.font='900 20px Arial';x.fillText('G',21,50);x.strokeStyle='#6dff1c';x.lineWidth=3;[[10,18,17,25],[17,18,10,25],[25,18,32,25],[32,18,25,25]].forEach(a=>{x.beginPath();x.moveTo(a[0],a[1]);x.lineTo(a[2],a[3]);x.stroke()});x.restore();if(g.shield){x.strokeStyle='#4ed8ff';x.lineWidth=3;x.beginPath();x.arc(p.x+21,p.y+27,35,0,7);x.stroke()}}
function end(){g.run=false;cancelAnimationFrame(raf);let m=Math.floor(g.dist),xp=Math.max(10,Math.min(120,Math.floor(m/9))),record=m>s.best,mission=g.passed>=5;if(record)s.best=m;s.runs++;s.totalCoins+=g.coins;if(mission){xp+=20;s.missions++}$('#resultHeadline').textContent=record?'НОВЫЙ РЕКОРД!':'ЗАБЕГ ОКОНЧЕН';$('#resultMeters').textContent=m;$('#resultCoins').textContent=g.coins;$('#resultXp').textContent=xp;$('#missionResult').textContent=mission?'🎯 Задание выполнено: +20 XP':`🎯 Задание: ${Math.min(g.passed,5)}/5`;$('#claim').disabled=false;$('#claim').style.opacity='1';$('#claim').dataset.c=g.coins;$('#claim').dataset.x=xp;$('#claim').dataset.m=m;persist();show('result')}
$('#claim').onclick=()=>{let b=$('#claim');if(b.disabled)return;let coins=Math.min(+b.dataset.c,75),xp=Math.min(+b.dataset.x,120);s.coins+=coins;s.xp+=xp;persist();b.disabled=true;b.style.opacity='.4';b.textContent='НАГРАДА ПОЛУЧЕНА';try{tg?.HapticFeedback?.notificationOccurred('success');tg?.sendData?.(JSON.stringify({type:'rush_result',meters:+b.dataset.m,coins,xp}))}catch(e){}toast(`+${coins} 🪙  +${xp} XP`)};
render();