
const tg=window.Telegram?.WebApp;try{tg?.ready();tg?.expand();tg?.setHeaderColor?.('#050807');tg?.setBackgroundColor?.('#030605')}catch(e){}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='goodigoo_rush_v03'; let S=JSON.parse(localStorage.getItem(KEY)||'{}');
S.coins??=350;S.xp??=0;S.best??=0;S.runs??=0;S.missions??=0;S.totalCoins??=0;S.dailyDay??=4;S.dailyClaimed??=false;S.inv??={shield:0,magnet:0,boost:0};
const NAME=tg?.initDataUnsafe?.user?.first_name||'GoodiGoo';
function save(){localStorage.setItem(KEY,JSON.stringify(S));render()}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1600)}
function show(id){$$('.screen').forEach(e=>e.classList.remove('active'));$('#'+id).classList.add('active');if(id==='rating')renderRank()}
$$('[data-screen]').forEach(b=>b.onclick=()=>show(b.dataset.screen));
function info(){const level=Math.floor(S.xp/100)+1,n=S.xp%100;let rank='Новичок';if(level>=2)rank='В теме';if(level>=3)rank='Свой';if(level>=5)rank='Ветеран';if(level>=7)rank='Элита';if(level>=10)rank='Легенда GoodiGoo';return{level,n,rank}}
function render(){const I=info();$('#wallet').textContent=S.coins;$('#shopWallet').textContent=S.coins;$('#best').textContent=S.best;$('#level').textContent=I.level;$('#runs').textContent=S.runs;$('#username').textContent=NAME;$('#profileLevel').textContent=I.level;$('#rankName').textContent=I.rank;$('#xpNow').textContent=I.n;$('#xpFill').style.width=I.n+'%';$('#profileBest').textContent=S.best;$('#profileRuns').textContent=S.runs;$('#profileCoins').textContent=S.coins;$('#profileMissions').textContent=S.missions;$('#ach100').classList.toggle('unlocked',S.best>=100);$('#achCoins').classList.toggle('unlocked',S.totalCoins>=25);$('#ach500').classList.toggle('unlocked',S.best>=500);let inv=[];if(S.inv.shield)inv.push('🛡️×'+S.inv.shield);if(S.inv.magnet)inv.push('🧲×'+S.inv.magnet);if(S.inv.boost)inv.push('🚀×'+S.inv.boost);$('#inventory').textContent=inv.join('  ')||'пусто';renderDays()}
function renderDays(){const vals=[100,150,200,250,300,350,500];$('#days').innerHTML=vals.map((v,i)=>`<div class="day ${i+1<S.dailyDay?'done':i+1===S.dailyDay?'current':''}">ДЕНЬ ${i+1}<b>🪙 ${v}</b></div>`).join('');$('#streak').textContent=S.dailyDay;$('#dailyBtn').disabled=S.dailyClaimed;$('#dailyBtn').style.opacity=S.dailyClaimed?'.45':'1';$('#dailyBtn').textContent=S.dailyClaimed?'УЖЕ ЗАБРАНО':'ЗАБРАТЬ СЕГОДНЯ'}
$('#dailyBtn').onclick=()=>{if(S.dailyClaimed)return;const v=[100,150,200,250,300,350,500][Math.min(S.dailyDay-1,6)];S.coins+=v;S.dailyClaimed=true;save();toast('+'+v+' GoodiCoin')};
$$('.shop-list button').forEach(b=>b.onclick=()=>{const p=+b.dataset.price;if(S.coins<p)return toast('Не хватает GoodiCoin');S.coins-=p;S.inv[b.dataset.item]++;save();toast('Буст куплен')});
function renderRank(){const a=[['SHADOW',Math.max(1105,S.best+420)],['NEO',Math.max(980,S.best+250)],['FASTBOY',Math.max(875,S.best+120)],[NAME,S.best]].sort((a,b)=>b[1]-a[1]);$('#rankList').innerHTML=a.map((x,i)=>`<div class="rank-row ${x[0]===NAME?'me':''}"><b>#${i+1}</b><span>${x[0]}</span><b>${x[1]} м</b></div>`).join('')}
const C=$('#canvas'),ctx=C.getContext('2d');let W=0,H=0,D=1,G=null,RAF=0,last=0;
function resize(){const r=C.getBoundingClientRect();D=Math.min(devicePixelRatio||1,2);C.width=Math.round(r.width*D);C.height=Math.round(r.height*D);W=r.width;H=r.height;ctx.setTransform(D,0,0,D,0,0)}
addEventListener('resize',resize);
function start(){show('game');setTimeout(()=>{resize();G={running:true,paused:false,speed:300,dist:S.inv.boost?20:0,coins:0,passed:0,shield:S.inv.shield?1:0,magnet:!!S.inv.magnet,p:{x:68,y:H-150,w:42,h:58,vy:0,ground:true},obs:[],cs:[],no:.9,nc:.45};if(S.inv.shield)S.inv.shield--;if(S.inv.magnet)S.inv.magnet--;if(S.inv.boost)S.inv.boost--;save();last=performance.now();cancelAnimationFrame(RAF);RAF=requestAnimationFrame(loop)},70)}
$('#playBtn').onclick=start;$('#againBtn').onclick=start;$('#pauseBtn').onclick=()=>{if(G){G.paused=!G.paused;$('#pauseBtn').textContent=G.paused?'▶':'Ⅱ'}};
C.addEventListener('pointerdown',()=>{if(G?.running&&!G.paused&&G.p.ground){G.p.vy=-610;G.p.ground=false;try{tg?.HapticFeedback?.impactOccurred('light')}catch(e){}}});
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function loop(t){if(!G?.running)return;const dt=Math.min((t-last)/1000,.032);last=t;if(!G.paused)update(dt);draw();RAF=requestAnimationFrame(loop)}
function update(dt){const g=G,p=g.p;g.speed+=dt*3.4;g.dist+=g.speed*dt/43;p.vy+=1550*dt;p.y+=p.vy*dt;const floor=H-94-p.h;if(p.y>=floor){p.y=floor;p.vy=0;p.ground=true}g.no-=dt;if(g.no<=0){const h=40+Math.random()*44;g.obs.push({x:W+25,y:H-94-h,w:34+Math.random()*20,h,passed:false});g.no=.9+Math.random()*.72}g.nc-=dt;if(g.nc<=0){const n=3+Math.floor(Math.random()*3);for(let i=0;i<n;i++)g.cs.push({x:W+30+i*34,y:H-158-Math.random()*90,r:9});g.nc=.78+Math.random()*.78}g.obs.forEach(o=>{o.x-=g.speed*dt;if(!o.passed&&o.x+o.w<p.x){o.passed=true;g.passed++}});g.cs.forEach(q=>{q.x-=g.speed*dt;if(g.magnet&&q.x<W*.75){q.x+=(p.x-q.x)*dt*4;q.y+=(p.y-q.y)*dt*4}});for(const o of g.obs){if(hit(p,o)){if(g.shield){g.shield=0;o.x=-999;toast('🛡️ Щит спас!')}else return end()}}g.cs=g.cs.filter(q=>{if(Math.hypot(p.x+p.w/2-q.x,p.y+p.h/2-q.y)<30){g.coins++;return false}return q.x>-20});g.obs=g.obs.filter(o=>o.x>-80);$('#meters').textContent=Math.floor(g.dist);$('#runCoins').textContent=g.coins;$('#mission').textContent=Math.min(g.passed,5)+'/5'}
function draw(){const g=G,p=g.p;let grad=ctx.createLinearGradient(0,0,0,H);grad.addColorStop(0,'#181039');grad.addColorStop(.5,'#101a31');grad.addColorStop(1,'#06100b');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);const scroll=(g.dist*2.4)%78;ctx.fillStyle='#0b1730';for(let i=-1;i<9;i++){const xx=i*78-scroll,hh=110+(i%4)*35;ctx.fillRect(xx,H-94-hh,62,hh)}ctx.strokeStyle='#59ff2438';ctx.lineWidth=1;for(let i=0;i<8;i++){ctx.beginPath();ctx.moveTo(W/2,H-205);ctx.lineTo(i*W/7,H-94);ctx.stroke()}ctx.fillStyle='#070b0b';ctx.fillRect(0,H-94,W,94);ctx.fillStyle='#315637';ctx.fillRect(0,H-96,W,3);g.obs.forEach(o=>{ctx.fillStyle='#242a30';ctx.fillRect(o.x,o.y,o.w,o.h);ctx.strokeStyle='#ff5d3d';ctx.lineWidth=2;ctx.strokeRect(o.x+3,o.y+3,o.w-6,o.h-6);ctx.beginPath();ctx.moveTo(o.x+6,o.y+6);ctx.lineTo(o.x+o.w-6,o.y+o.h-6);ctx.moveTo(o.x+o.w-6,o.y+6);ctx.lineTo(o.x+6,o.y+o.h-6);ctx.stroke()});g.cs.forEach(q=>{ctx.beginPath();ctx.arc(q.x,q.y,q.r,0,Math.PI*2);ctx.fillStyle='#ffc52b';ctx.shadowBlur=12;ctx.shadowColor='#ffc52b';ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#6d4a00';ctx.font='bold 11px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('G',q.x,q.y)});ctx.save();ctx.translate(p.x,p.y);ctx.shadowBlur=18;ctx.shadowColor='#6cff20';ctx.fillStyle='#0a0e0b';ctx.beginPath();ctx.arc(21,20,22,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#111912';ctx.fillRect(7,34,29,24);ctx.fillStyle='#6dff1c';ctx.font='900 20px Arial';ctx.textAlign='center';ctx.fillText('G',21,51);ctx.strokeStyle='#6dff1c';ctx.lineWidth=3;[[10,18,17,25],[17,18,10,25],[25,18,32,25],[32,18,25,25]].forEach(a=>{ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(a[2],a[3]);ctx.stroke()});ctx.restore();if(g.shield){ctx.strokeStyle='#4ed8ff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x+21,p.y+27,35,0,Math.PI*2);ctx.stroke()}}
function end(){G.running=false;cancelAnimationFrame(RAF);const m=Math.floor(G.dist),mission=G.passed>=5;let xp=Math.max(10,Math.min(100,Math.floor(m/9)));if(mission)xp+=20;const record=m>S.best;if(record)S.best=m;S.runs++;S.totalCoins+=G.coins;if(mission)S.missions++;$('#resultTitle').textContent=record?'НОВЫЙ РЕКОРД!':'ЗАБЕГ ОКОНЧЕН';$('#resultMeters').textContent=m;$('#resultCoins').textContent=G.coins;$('#resultXp').textContent=xp;$('#missionResult').textContent=mission?'🎯 Задание выполнено: +20 XP':'🎯 Задание: '+Math.min(G.passed,5)+'/5';const b=$('#claimBtn');b.disabled=false;b.style.opacity='1';b.textContent='ЗАБРАТЬ НАГРАДУ';b.dataset.c=G.coins;b.dataset.x=xp;b.dataset.m=m;save();show('result')}
$('#claimBtn').onclick=()=>{const b=$('#claimBtn');if(b.disabled)return;const coins=Math.min(+b.dataset.c,75),xp=Math.min(+b.dataset.x,120);S.coins+=coins;S.xp+=xp;save();b.disabled=true;b.style.opacity='.45';b.textContent='НАГРАДА ПОЛУЧЕНА';try{tg?.HapticFeedback?.notificationOccurred('success');tg?.sendData?.(JSON.stringify({type:'rush_result',meters:+b.dataset.m,coins,xp}))}catch(e){}toast('+'+coins+' 🪙  +'+xp+' XP')};
render();
